#######################################
##   YNAB BUDDY CONFIGURATION FILE   ##
#######################################

# This file tells ynab-buddy how to read your bank's files.
#
# To learn how to use this file, check out:
# https://github.com/nielsmaerten/ynab-buddy/blob/main/docs/how-to-configure.md

import_from: "c:/users/test/downloads"
search_subfolders: true

bank_transaction_files:
  - account_name: BNP Checking Account
    pattern: BNP-export-IBAN01233456789-*.csv
    parser: bnp-checking-parser
    ynab_account_id: 3c8922e0-625d-423b-ab77-810edfc460b2
    ynab_budget_id: 1c8cdd9e-c923-4e39-9960-28664a2cd4ae
    ynab_flag_color: purple
    upload: true
    save_parsed_file: false
    delete_original_file: true

parsers:
  - name: bnp-checking-parser
    header_rows: 2
    footer_rows: 0
    delimiter: ","
    columns: [skip, skip, memo, date, inflow, skip]
    date_format: M/d/YYYY

upload_to_ynab:
  upload_transactions: false
  ynab_token: ABC12345

# When you're done configuring, delete the next line:
configuration_done: false
