# If undefined, interactively ask for the folder or press enter to use working dir
import_from: "c:/users/test/downloads"
search_subfolders: false

# At least 1 of these is required
bank_transaction_files:
  # the name is just for users, the script ignores it
  - account_name: BNP Checking Account
    # pattern is a glob pattern that will collect files from the import folder
    pattern: BNP-export-IBAN01233456789-*.csv
    ## parser tells which parser to use for any file that matches this pattern
    parser: bnp-checking-parser

    ## required to upload to ynab, ingored if the file isn't uploaded
    ynab_account_id: ABC1234
    ynab_budget_id: XYZ7890
    ynab_flag_color: purple

    ## additional settings, not required
    ## if undefined, default to 'upload_transactions' in the ynab section
    upload: false
    ## false by default, if true, save the parse result using a unique name
    save_parsed_file: true
    ## false by default, if true, delete the original file after processing
    ## if true, either upload or save must be true, otherwise it will default back to false (don't delete)
    delete_original_file: true

parsers:
  - name: bnp-checking-parser
    header_rows: 2
    footer_rows: 0
    delimiter: ","
    columns: [skip, skip, Memo, Date, Inflow, skip]
    date_format: "%m/%d/%Y"

upload_to_ynab:
  upload_transactions: false
  ynab_token: ABC12345

# Delete the following line:
show_config_prompt: true
